### ISSUE TITLE
Kermits #127 - Peer-to-peer Code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [Amita-Roy/Enumerable_Methods#3]
**This project is really impressive. Great job.** 

- You've tested extensively with a very large number of tests.
- You have made full use of RSpec matchers, such as (be_nil, raise_error, etc.) and not just stuck to eql().
- You've made use of the #context keyword to specify behaviours under certain conditions.
- In your tests, you've referred both to the original Enumerable methods and to your own expectations of the methods' results.

**Comment by amita-roy** [comment]
Thanks for the feedback team. Completed this project hence closing the issue.
